In [14]:
# Importing the modules:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
from scipy.spatial import distance

In [68]:
def read_xyz(file_path, skiplines, skipcol):
    """Reading the atomic positions and normalizes
    skiplines = 3 for XYZ, 8 for poscar
    skipcol = 1 for xyz, 0 for poscar
    """
    with open(file_path, 'r') as file:
        lines = file.readlines()[skiplines:]  # Skip the first two lines (atom count and comment)
        coordinates = [list(map(float, line.split()[skipcol:skipcol+4])) for line in lines]
    pos = np.array(coordinates)
    pos = pos/np.max(np.abs(pos)) + 1; print(np.max(pos))
    pos = pos/np.max(np.abs(pos))
    return pos

def hausdorff_distance(set1, set2):
#     set1 = set1/np.max(set1)
#     set2 = set2/np.max(set2)
    distance_matrix = distance.cdist(set1, set2)
    directed_hausdorff_1_to_2 = np.max(np.min(distance_matrix, axis=1))
    directed_hausdorff_2_to_1 = np.max(np.min(distance_matrix, axis=0))
    return distance_matrix, directed_hausdorff_1_to_2, directed_hausdorff_2_to_1, max(directed_hausdorff_1_to_2, directed_hausdorff_2_to_1)

In [69]:
os.system('ls')

chiral.ipynb
CoSi_10x10x10.xyz
CoSi_1x1x1_22746.xyz
CoSi_1x1x1_90_rotation.xyz
CoSi_1x1x1_chiral_wall.xyz
CoSi_1x1x1_distorted.xyz
CoSi_1x1x1_trans5.vasp
CoSi_1x1x1_trans5.xyz
CoSi_1x1x1.vasp
CoSi_1x1x1_X_mirror.vasp
CoSi_1x1x1_X_mirror.xyz
CoSi_1x1x1.xyz
CoSi_1x1x1_Y_mirror.xyz
CoSi_1x1x1_Z_mirror.xyz
CoSi_2x2x2_22746.xyz
CoSi_3x3x3_X_mirror.xyz
CoSi_3x3x3.xyz


0

In [71]:
# Replace 'file1.xyz' and 'file2.xyz' with your XYZ file paths
xyz_file1 = 'CoSi_1x1x1.xyz'
xyz_file2 = 'CoSi_1x1x1_X_mirror.xyz'

# Read coordinates from XYZ files
set1 = read_xyz(xyz_file1, 2, 1)
set2 = read_xyz(xyz_file2, 2, 1)
# set2 = read_xyz(xyz_file2, 8, 0)
print(set1, '\n')
print(set2, '\n')
# Calculate and print Hausdorff distance
matrix, val12, val21, distance_value = hausdorff_distance(set1, set2)
print("Distance matrix:\n", matrix, "\nShape:", matrix.shape)
print("1 to 2", val12)
print("2 to 1", val21)
print(f'Hausdorff Distance: {distance_value}')

2.0
2.0
[[1.         0.8781207  0.7072931 ]
 [0.8781207  0.7072931  1.        ]
 [0.7072931  1.         0.8781207 ]
 [0.5854138  0.5854138  0.5854138 ]
 [0.59164026 0.70106664 0.88434716]
 [0.70106664 0.88434716 0.59164026]
 [0.88434716 0.59164026 0.70106664]
 [0.99377354 0.99377354 0.99377354]] 

[[0.93951322 0.55516658 0.53024339]
 [0.95729502 0.53024339 0.57294837]
 [0.98221821 0.57294837 0.55516658]
 [1.         0.5124616  0.5124616 ]
 [0.99909158 0.52933497 0.556075  ]
 [0.98312663 0.556075   0.51337002]
 [0.95638659 0.51337002 0.52933497]
 [0.94042164 0.57203995 0.57203995]] 

Distance matrix:
 [[0.37323533 0.37535429 0.34145105 0.41432583 0.38015684 0.37630347
  0.40818413 0.33989472]
 [0.49757692 0.46902907 0.47619488 0.53898755 0.49332794 0.52029021
  0.51503134 0.4531276 ]
 [0.61059117 0.6134349  0.60187729 0.67607515 0.64061327 0.63733555
  0.64846572 0.575486  ]
 [0.35964576 0.37615795 0.39815075 0.42723034 0.41849123 0.40524877
  0.38204183 0.35551131]
 [0.51738951 0.50975